# Generated by Django 4.0.4 on 2022-04-17 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=40)),
                ('description', models.TextField(max_length=10000)),
                ('slug', models.SlugField(blank=True, null=True)),
            ],
        ),
    ]
