# Generated by Django 4.0.4 on 2022-05-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='icon',
        ),
        migrations.AddField(
            model_name='services',
            name='description_ar',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='description_en',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icon-services/'),
        ),
        migrations.AddField(
            model_name='services',
            name='name_ar',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='services',
            name='name_en',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
