# Generated by Django 4.0.4 on 2022-04-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='services',
            old_name='description',
            new_name='description_ar',
        ),
        migrations.RenameField(
            model_name='services',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.RemoveField(
            model_name='services',
            name='icon',
        ),
        migrations.AddField(
            model_name='services',
            name='description_en',
            field=models.TextField(default='name', max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icon-services/'),
        ),
        migrations.AddField(
            model_name='services',
            name='name_en',
            field=models.CharField(default='name', max_length=40),
            preserve_default=False,
        ),
    ]
