# Generated by Django 4.0.4 on 2022-04-20 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Marketia', '0002_services_description_ar_services_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='icon',
        ),
        migrations.AddField(
            model_name='services',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='icon-services/'),
        ),
    ]
