# Generated by Django 4.0.4 on 2022-05-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='image_detail_body',
        ),
        migrations.AddField(
            model_name='post',
            name='image_detail_head',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_home',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_list',
            field=models.ImageField(blank=True, null=True, upload_to='post/'),
        ),
    ]
