# Generated by Django 4.0.4 on 2022-05-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_image_post_image_detail_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_three',
            field=models.TextField(default='def'),
            preserve_default=False,
        ),
    ]
