# Generated by Django 4.0.4 on 2022-05-15 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_description_three'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description_three_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='description_three_en',
            field=models.TextField(null=True),
        ),
    ]
